apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-tests-parent-image-with-both-tag-digest-ellt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-tests-parent-image-with-both-tag-digest-ellt
    app.kubernetes.io/part-of: test-app-864
  name: e2e-tests-parent-image-with-both-tag-digest-ellt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: e2e-tests-parent-image-with-both-tag-digest-ellt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: e2e-tests-parent-image-with-both-tag-digest-ellt
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-864/e2e-tests-parent-image-with-both-tag-digest-ellt@sha256:bf3187ed7d3125c8a0341b46c6ab937ddf5bdbe30af985276ad94d66eeb912ae
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
