apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: retrodep-fgv3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: retrodep-fgv3
    app.kubernetes.io/part-of: test-app-864
  name: retrodep-fgv3
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-retrodep
      app.kubernetes.io/instance: retrodep-fgv3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-retrodep
        app.kubernetes.io/instance: retrodep-fgv3
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-864/retrodep-fgv3@sha256:8c680b6ca7a1d51e7c532a61f841bc3196d2279b5ef629b19eb1ddadccba8cea
        name: my-retrodep
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
