apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fbc-sample-repo-0iwh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fbc-sample-repo-0iwh
    app.kubernetes.io/part-of: test-app-864
  name: fbc-sample-repo-0iwh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: fbc
      app.kubernetes.io/instance: fbc-sample-repo-0iwh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fbc
        app.kubernetes.io/instance: fbc-sample-repo-0iwh
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-864/fbc-sample-repo-0iwh@sha256:b67fec241c63475eba0b88d13a005aecba59ffe177b2be2dc9bb7e5e026694be
        name: fbc
        ports:
        - containerPort: 50051
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
status: {}
