apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-tests-parent-image-with-digest-only-fyvc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-tests-parent-image-with-digest-only-fyvc
    app.kubernetes.io/part-of: test-app-864
  name: e2e-tests-parent-image-with-digest-only-fyvc
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: e2e-tests-parent-image-with-digest-only-fyvc
status:
  loadBalancer: {}
